/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in a local app. It is committed here so the scaffold is explicit from the first run.
